defaults:
  - base_io

tournaments_gdrive: https://docs.google.com/spreadsheets/d/e/2PACX-1vQXttFmSuHPQHyBvOrCDsYpEB1lDC7O9In0HpZNA_eYu6d8_JqBWdF9audjzJYiCVLiTor-gLpyjiR2/pub?output=xlsx
tournaments_spreadsheet_id: 1SfzfFCL-WTtMeZ-Vt8hAjBSl8nGPHFv4S3lMb_B4EUI
