sanction_factor: 0.5
rating_factor: 2.0
category_expected_factor: 0.5
category_unexpected_factor: 1.5
tournament_window_to_activate: 4
tournaments_to_activate: 2
tournament_window_to_inactivate: 4
categories_thresholds:
  - 1300  # minimo de primera
  - 700  # minimo de segunda
  - 400  # minimo de tercera
masters_N_tournaments_to_consider: 8
masters_N_classified_to_list: 10000
