io:
    data_folder: data/
    tournaments_filename: Liga Dos Orillas 2019 - Carga de partidos.xlsx
    rankings_filename: Liga Dos Orillas 2019 - Rankings Crudos.xlsx
    log_filename: log2019.xlsx
    publish_filename: Torneo NN 2019 para publicar.xlsx
    tournaments_gdrive: https://docs.google.com/spreadsheets/d/e/2PACX-1vQh5XRw5FKbXLWehFUHKL69a8TCKv66-GaZcoxBKHREnSqFrMkSYIslLp7CmehC1SJ1TkQPWGKQFjNr/pub?output=xlsx
    tournaments_spreadsheet_id: 1e7UBtVbRQ82FmfUFIEM3DRk1EnZwG9IPKWKnybsNrBw
    temporal_spreadsheet_id: 1R_1__G0DAZP3_T4LCGjfcr_Gs9CXeRBQlgbUwa_We3k
    players_temp_file: temp_players.pickle
    ranking_temp_file: temp_ranking.pickle

sheetname:
    players: Jugadores
    initial_ranking: Ranking inicial
    tournaments_key: Partidos
    bonus_details_key: Bonus
    rating_details_key: Rating
    rankings_key: Ranking
    histories: Historiales 2019
    championship_key: Campeonato
    statistics_key: Estadisticas

labels:
    PID: PID
    Player: Jugador
    Association: Asociación
    City: Ciudad
    Last Tournament: Último Torneo
    Bonus Points: Puntos de Campeonato
    Rating Points: Nivel de Juego
    Best Round: Mejor Ronda
    Round: Instancia
    Winner: Ganador
    Loser: Perdedor
    Winner Points: Puntos Ganador
    Loser Points: Puntos Perdedor
    Category: Categoría
    Participation Points: Puntos por participar
    Total Points: Total puntos
    Active Player: Jugador Activo
    Date: Fecha
    Location: Lugar
    Tournament name: Nombre del torneo
    Tournament: Torneo
    Participations: Torneos Jugados
    Position: Posición
    Difference: Diferencia
    tid: ID torneo

activeplayer:
    True: activo
    False: inactivo

roundnames:
    final: final
    champion: primero
    second: segundo
    third: tercero
    fourth: cuarto
    third place playoff: tercer puesto

aux:
    flag add bonus: to_add_bonus_points
    flag bonus sanction: to_subtract_bonus_points
    sanction factor: 0.5
    flag promotion: promotion
    rating factor: 2.0
    category expected factor: 0.5
    category unexpected factor: 1.5
    tournament window to activate: 4
    tournaments to activate: 2
    tournament window to inactivate: 4
