io:
    data_folder: data/
    tournaments_filename: Liga Dos Orillas 2018 prueba - Partidos.xlsx
    rankings_filename: Liga Dos Orillas 2018 prueba - Rankings Crudos.xlsx
    log_filename: log.xlsx
    publish_filename: Torneo NN para publicar.xlsx
    tournaments_gdrive: https://docs.google.com/spreadsheets/d/e/2PACX-1vTWBSRRCCBqtGTcETManYdsM9DMX3Jz6VQTVt5mAMmON8M7cfzZwK0a0CUvvFrFsjW-usKxHw7m_aiV/pub?output=xlsx
    tournaments_spreadsheet_id: 1dnu-_xGlA-5N-01bZN554l6N-9SD6Ct1UOCJ9tUWXRs
    temporal_spreadsheet_id: 1dnu-_xGlA-5N-01bZN554l6N-9SD6Ct1UOCJ9tUWXRs

sheetname:
    players: Jugadores
    initial_ranking: Ranking inicial
    tournaments_key: Partidos
    bonus_details_key: Bonus
    rating_details_key: Rating
    rankings_key: Ranking
    histories: Historiales
    championship_key: Campeonato

labels:
    PID: PID
    Player: Jugador
    Association: Asociación
    City: Ciudad
    Last Tournament: Último Torneo
    Bonus Points: Puntos de Campeonato
    Rating Points: Nivel de Juego
    Best Round: Mejor Ronda
    Winner: Ganador
    Loser: Perdedor
    Winner Points: Puntos Ganador
    Loser Points: Puntos Perdedor
    Category: Categoría
    Participation Points: Puntos por participar
    Total Points: Total puntos
    Active Player: Jugador Activo
    Date: Fecha
    Location: Lugar
    Tournament name: Nombre del torneo
    Tournament: Torneo
    Participations: Torneos Jugados
    Position: Posición
    Difference: Diferencia
    tid: ID torneo

activeplayer:
    True: activo
    False: inactivo

roundnames:
    final: final
    champion: primero
    second: segundo
    third: tercero
    fourth: cuarto
    third place playoff: tercer puesto

aux:
    flag add bonus: to_add_bonus_points
    flag promotion: promotion
    rating factor: 2.0
    category expected factor: 0.5
    category unexpected factor: 2.0
    tournament window to activate: 6
    tournaments to activate: 2
    tournament window to inactivate: 5
