io:
    data_folder: data_rtt/
    tournaments_filename: Liga Dos Orillas 2020 - Carga de partidos.xlsx
    rankings_filename: Liga Dos Orillas 2020 - Rankings Crudos.xlsx
    publish_filename: Torneo NN para publicar.xlsx
    tournaments_gdrive: https://docs.google.com/spreadsheets/d/e/2PACX-1vRQQzsvkO7MJu6s05ijb5Rwm71DXcIgEOXWNuv81nsSn1W1wG5ht0DPJD82IJQdpq6KfWL1mXwdj0HF/pub?output=xlsx
    tournaments_spreadsheet_id: 1fo1yljugseIfOT-ALgtSllmZrrtZ3aRuc_gRc05OT60
    temporal_spreadsheet_id: 134W18TVOjpUVs25IOoxHMVZud8Ucaxe44XJutzTI1Ak
    players_temp_file: temp_players.pickle
    ranking_temp_file: temp_ranking.pickle
    players_pickle: players.pk
    tournaments_pickle: tournaments.pk
    rankings_pickle: rankings.pk
    published_on_web_spreadsheets_id:
      - 1QhZZqltiD9KUXCeeT9IwcR7GH-HQ-V49b7ISVLkUlCY  # partidos
      - 1kW7IocinP1WxtK0KRC84sXxjuQmaewsibN6H9TW6e-g  # nivel de juego
      - 1r-UzvU8yUdfn0CLlbWKVJe2-EaBNFCy2WbaSjF10538  # detalles nivel de juego
      - 1E_FsouAAnqVsTJ2pEJ8lzCkqtzYKBXO04a4OMmtvBYs  # campeonato primera
      - 1oMcD1oJ06aN4rUNIDGNs-Z_hhGSPLNwX9lyw2iIKQW4  # campeonato segunda
      - 1uKCnlbvp_r2Qr-J-H8uO90DERAjohqcZZ5o64rePss8  # campeonato tercera
      - 1o7pIa8BERQk5baCvWR1j5UZAEUsDCv5Tdowu-uSUZxI  # campeonato cuarta
      - 1CThfYo10XqXubDoZ1zvBS5yPQ40OW4-WDB7dLpVyGI0  # campeonato quinta
      - 1_BONV3xFNLtdunP_PqdvG2HksRAVbNiX_LQmU5c1FLw  # detalles campeonato

sheetname:
    players: Jugadores
    initial_ranking: Ranking Torneo 00 2020
    tournaments_key: Partidos
    championship_details_key: Log Campeonato
    rating_details_key: Log Rating
    rankings_key: Ranking
    histories: Historiales 2020
    championship_key: Campeonato
    statistics_key: Estadisticas

labels:
    tid: ID Torneo
    pid: ID Jugador
    Player: Jugador
    Association: Afiliación
    City: Ciudad
    Last Tournament: Último Torneo
    Championship Points: Puntos de Campeonato
    Rating: Nivel de Juego
    Best Round: Mejor Ronda
    Round: Instancia
    Winner: Ganador
    Loser: Perdedor
    Winner Points: Puntos Ganador
    Loser Points: Puntos Perdedor
    Category: Categoría
    Total Points: Total puntos
    Active Player: Jugador Activo
    Date: Fecha
    Location: Lugar
    Tournament name: Nombre del torneo
    Tournament: Torneo
    Participations: Torneos Jugados
    Position: Posición
    Difference: Diferencia
    Selected Tournaments: Puntos sumados
    Points CAT:
      - Puntos Primera
      - Puntos Segunda
      - Puntos Tercera
      - Puntos Cuarta
      - Puntos Quinta

activeplayer:
    True: activo
    False: inactivo

roundnames:
    final: final
    champion: primero
    second: segundo
    third: tercero
    fourth: cuarto
    third place playoff: tercer puesto

aux:
    sanction factor: 0.5
    rating factor: 2.0
    category expected factor: 0.5
    category unexpected factor: 1.5
    tournament window to activate: 4
    tournaments to activate: 2
    tournament window to inactivate: 4
    categories thresholds:
      - 1500  # minimo de primera
      - 1100  # minimo de segunda
      - 800   # minimo de tercera
      - 600   # minimo de cuarta
    masters N tournaments to consider: 8
    masters N classified to list: 10000
    initial tid: S2020T00

default:
    tournament_name: Inicial 2020 - Liga Dos Orillas
    date: 2020 01 01
    location: No aplica
    category:
