io:
    data_folder: data/
    tournaments_filename: Liga Dos Orillas 2019 - Carga de partidos.xlsx
    rankings_filename: Liga Dos Orillas 2019 - Rankings Crudos.xlsx
    log_filename: log2019.xlsx
    publish_filename: Torneo NN 2019 para publicar.xlsx
    tournaments_gdrive: https://docs.google.com/spreadsheets/d/e/2PACX-1vQh5XRw5FKbXLWehFUHKL69a8TCKv66-GaZcoxBKHREnSqFrMkSYIslLp7CmehC1SJ1TkQPWGKQFjNr/pub?output=xlsx
    tournaments_spreadsheet_id: 1e7UBtVbRQ82FmfUFIEM3DRk1EnZwG9IPKWKnybsNrBw
    temporal_spreadsheet_id: 1R_1__G0DAZP3_T4LCGjfcr_Gs9CXeRBQlgbUwa_We3k
    players_temp_file: temp_players.pickle
    ranking_temp_file: temp_ranking.pickle
    published_on_web_spreadsheets_id:
      - 1ERmL9bj3mvsF1pfDQEAhiKzjaEOxvUX2EqakO5HIkJY  # partidos
      - 1HC7HdmT8tYlwLDmObDDoHfNYIxAUkLiY81J8YPm3xRo  # nivel de juego
      - 118RnRL-YFEB3eg78MM_lDwCrbYzJ1p5MUUVHDpCgWFs  # detalles nivel de juego
      - 1hhz3w-Zm7R7w1x2eWhj1BynU76Eo7R6EDB8RZH7m7QQ  # masters primera
      - 1kUSmsmBXSTW-UcFrj_ZPWohIFlplfMdo3j5JQWs3TrY  # masters segunda
      - 1CO-D1P1FYEYudKKZ6oGH9KBoodRKfaGj9zD3BfsSMlw  # masters tercera
      - 1jGXffNwVW93edpm1zzIBGLN3KJi46qo9lzcfv1AnO_s  # masters cuarta

sheetname:
    players: Jugadores
    initial_ranking: Ranking inicial
    tournaments_key: Partidos
    bonus_details_key: Bonus
    rating_details_key: Rating
    rankings_key: Ranking
    histories: Historiales 2019
    championship_key: Campeonato
    statistics_key: Estadisticas

labels:
    PID: PID
    Player: Jugador
    Association: Asociación
    City: Ciudad
    Last Tournament: Último Torneo
    Bonus Points: Puntos de Campeonato
    Rating Points: Nivel de Juego
    Best Round: Mejor Ronda
    Round: Instancia
    Winner: Ganador
    Loser: Perdedor
    Winner Points: Puntos Ganador
    Loser Points: Puntos Perdedor
    Category: Categoría
    Participation Points: Puntos por participar
    Total Points: Total puntos
    Active Player: Jugador Activo
    Date: Fecha
    Location: Lugar
    Tournament name: Nombre del torneo
    Tournament: Torneo
    Participations: Torneos Jugados
    Position: Posición
    Difference: Diferencia
    tid: ID torneo

activeplayer:
    True: activo
    False: inactivo

roundnames:
    final: final
    champion: primero
    second: segundo
    third: tercero
    fourth: cuarto
    third place playoff: tercer puesto

aux:
    flag add bonus: to_add_bonus_points
    flag bonus sanction: to_subtract_bonus_points
    sanction factor: 0.5
    flag promotion: promotion
    rating factor: 2.0
    category expected factor: 0.5
    category unexpected factor: 1.5
    tournament window to activate: 4
    tournaments to activate: 2
    tournament window to inactivate: 4
    categories thresholds:
      - 1500  # minimo de primera
      - 1250  # minimo de segunda
      - 1000  # minimo de tercera
    masters N tournaments to consider: 8
    masters N classified to list: 10000
